global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8082"]

  - job_name: "presence-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["presence-service:8083"]

  - job_name: "chat-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["chat-service:8084"]

  - job_name: "websocket-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["websocket-service:8085"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-auth:5432", "postgres-users:5432"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "cassandra"
    static_configs:
      - targets: ["cassandra:9042"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]
