server:
  port: 8086

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  media:
    upload-dir: /tmp/uploads
    max-file-size: 10485760 # 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.chatapp.media: DEBUG
